name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Hello World
      run: echo Hello, world!

    - name: Lint with flake8
      if: github.event_name == 'push' && contains(github.event.head_commit.message, 'lint')
      run: |
        pip install flake8
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
